version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "bloomchain"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "bloomchain"
  bloomchain:
    restart: unless-stopped
    command: mix phx.server --no-halt
    volumes:
      - ./data:/opt/host
    depends_on:
      - elasticsearch
      - postgres
    ports:
      - "4000:4000"
    image: "bloomchain/bloomchain:master"
    environment:
      PORT: "4000"
      MIX_ENV: "prod"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"

      AWS_ACCESS_KEY_ID: "AKIAJAYL3BSTGFSEDQFQ"
      AWS_BUCKET: "bloomchain-cdn"
      AWS_REGION: "eu-central-1"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

      DATABASE_URL: "postgres://bloomchain:${DB_PASS}@postgres:5432/bloomchain"

      TZ: "Europe/Moscow"

      ES_URL: "https://elasticsearch:9200"
      ES_USER: "elastic"
      ES_PASSWORD: "${ES_PASSWORD}"

      POSTMARK_API_KEY: "${POSTMARK_API_KEY:?POSTMARK_API_KEY is required}"
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  elasticsearch-data:
    driver: local
  postgres-data:
    driver: local