use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# BloomchainWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :bloomchain, BloomchainWeb.Endpoint,
  load_from_system_env: true,
  # http: [compress: true],
  url: [scheme: "https", host: "new.bloomchain.ru", port: 443],
  # url: [scheme: "https", host: "bloomchain.herokuapp.com", port: 443, compress: true],
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

# Configure your database
config :bloomchain, Bloomchain.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

# Do not print debug messages in production
config :logger, level: :debug

# Arc Image Upload
config :arc,
  storage: Arc.Storage.S3,
  bucket: {:system, "AWS_BUCKET"},
  version_timeout: 60_000,
  virtual_host: true

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: [{:system, "AWS_REGION"}, :instance_role]

config :ex_aws, :hackney_opts,
  follow_redirect: true,
  recv_timeout: 60_000

config :bloomchain, Bloomchain.ElasticsearchCluster,
  url: System.get_env("ES_URL"),
  username: System.get_env("ES_USER"),
  password: System.get_env("ES_PASSWORD")

config :sentry,
  dsn: "https://4ceb6862d2b6458fa32dd6f4644b57fc@o252637.ingest.sentry.io/5273561",
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!,
  tags: %{
    env: "production"
  },
  included_environments: [:prod]
  
import_config "scheduler.exs"
